@echo OFF
setlocal
set SCRIPT_CURRENT_DIR=%~dp0
set PATH=PATH=%SCRIPT_CURRENT_DIR%\mingw64\bin;%SCRIPT_CURRENT_DIR%\usr\local\bin;%SCRIPT_CURRENT_DIR%\usr\bin;%PATH%
set HOME=%SCRIPT_CURRENT_DIR%\home\%USERNAME%
IF NOT EXIST %HOME% mkdir %HOME%
set MINGW_CHOST=x86_64-w64-mingw32
set MINGW_PACKAGE_PREFIX=mingw-w64-x86_64
set MINGW_PREFIX=/mingw64
set MSYSTEM_CARCH=x86_64
set MSYSTEM_CHOST=x86_64-w64-mingw32
set MSYSTEM_PREFIX=/mingw64
set MSYSTEM=MINGW64
%SCRIPT_CURRENT_DIR%\usr\bin\bash.exe
endlocal