@echo OFF
setlocal
set SCRIPT_CURRENT_DIR=%~dp0
set PATH=PATH=%SCRIPT_CURRENT_DIR%\mingw32\bin;%SCRIPT_CURRENT_DIR%\usr\local\bin;%SCRIPT_CURRENT_DIR%\usr\bin;%PATH%
set HOME=%SCRIPT_CURRENT_DIR%\home\%USERNAME%
IF NOT EXIST %HOME% mkdir %HOME%
set MINGW_CHOST=i686-w64-mingw32
set MINGW_PACKAGE_PREFIX=mingw-w64-i686
set MINGW_PREFIX=/mingw32
set MSYSTEM_CARCH=i686
set MSYSTEM_CHOST=i686-w64-mingw32
set MSYSTEM_PREFIX=/mingw32
set MSYSTEM=MINGW32
%SCRIPT_CURRENT_DIR%\usr\bin\bash.exe
endlocal