#! bash -uvx
rm -rf .qmake* debug release Makefile* *_plugin_import.cpp ui_*.h
$MSYSTEM_PREFIX/qt5-static/bin/qmake.exe $1.pro
mingw32-make.exe -f Makefile.Release || exit 1
for i in release/*.a; do
  if [ -f "$i" ]; then cp -p "$i" .; fi
done
for i in release/*.dll; do
  if [ -f "$i" ]; then cp -p "$i" .; fi
done
for i in release/*.exe; do
  if [ -f "$i" ]; then cp -p "$i" .; fi
done
